name: digitalocean
description: An Sdk for the DigitalOcean API.
version: 0.0.3+2
homepage: https://github.com/apollocode-ca/digitalocean_sdk

environment:
  sdk: ">=2.18.4 <4.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  collection: ^1.17.1
  http: ^0.13.5